#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}


set timeout -1
set var1 {$Test458367}
set var2 {$Test458367}
spawn ./newUserCert.sh testuser1 $var1 $var2 testuser@testca.com n
expect -re "Creating PFX for Windows"